### ISSUE TITLE
How to invoke PublicKeyManager

### ISSUE THREAD

**Issue by praveenkrjha** [basdecort/Xamarin#1]
Hi Bas, I took your PublicKeyManager class implementation and put that in my Xamarin.Android project.
However, it is not being called. How do I trigger it?

Thanks,
Praveen

**Comment by basdecort** [comment]
Hi Praveen,

In order to activate the PublicKeyManager, you need to take a few steps:

1. Add the PublicKeyManager to the Default (TLS) context. See the code below or PublicKeyHandler:SetHandler():

```
 var algoritm = TrustManagerFactory.DefaultAlgorithm;
 var trustManagerFactory = TrustManagerFactory.GetInstance(algoritm);
trustManagerFactory.Init((KeyStore)null);

var tm = new ITrustManager[] { new PublicKeyManager() };
SSLContext sslContext = SSLContext.GetInstance("TLS");
sslContext.Init(null, tm, null);
SSLContext.Default = sslContext;

HttpsURLConnection.DefaultSSLSocketFactory = sslContext.SocketFactory;
```
2. The next step is to create an instance of HttpClient that uses the AndroidClientHandler. Only when using the AndroidClientHandler combined with HttpClient, the PublicKeyManager will be called:

`var httpClient = new HttpClient(new AndroidClientHandler());`

3. Use the httpClient instance to make calls to your webservice. For example:

`var result = await httpClient.GetAsync("https://yourWebserviceUrl.com");`

Please let met know if you have additional questions.

Bas
